INSERT INTO knowledge_entities
  (id, domain, type, name_th, aliases, description, attributes, relations, source, confidence, version)
VALUES
  ('geo-province-001','geo','province','กรุงเทพมหานคร','["กรุงเทพมหานคร","กรุงเทพ","กทม"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.90,'v1'),
  ('geo-province-002','geo','province','กระบี่','["กระบี่"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-003','geo','province','กาญจนบุรี','["กาญจนบุรี"]','จังหวัดในภาคตะวันตกของประเทศไทย','{"region":"ภาคตะวันตก"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-004','geo','province','กาฬสินธุ์','["กาฬสินธุ์"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-005','geo','province','กำแพงเพชร','["กำแพงเพชร"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-006','geo','province','ขอนแก่น','["ขอนแก่น"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-007','geo','province','จันทบุรี','["จันทบุรี"]','จังหวัดในภาคตะวันออกของประเทศไทย','{"region":"ภาคตะวันออก"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-008','geo','province','ฉะเชิงเทรา','["ฉะเชิงเทรา","แปดริ้ว"]','จังหวัดในภาคตะวันออกของประเทศไทย','{"region":"ภาคตะวันออก"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-009','geo','province','ชลบุรี','["ชลบุรี"]','จังหวัดในภาคตะวันออกของประเทศไทย','{"region":"ภาคตะวันออก"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-010','geo','province','ชัยนาท','["ชัยนาท"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-011','geo','province','ชัยภูมิ','["ชัยภูมิ"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-012','geo','province','ชุมพร','["ชุมพร"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-013','geo','province','เชียงราย','["เชียงราย"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-014','geo','province','เชียงใหม่','["เชียงใหม่"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-015','geo','province','ตรัง','["ตรัง"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-016','geo','province','ตราด','["ตราด"]','จังหวัดในภาคตะวันออกของประเทศไทย','{"region":"ภาคตะวันออก"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-017','geo','province','ตาก','["ตาก"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-018','geo','province','นครนายก','["นครนายก"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-019','geo','province','นครปฐม','["นครปฐม"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-020','geo','province','นครพนม','["นครพนม"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-021','geo','province','นครราชสีมา','["นครราชสีมา","โคราช"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.85,'v1'),
  ('geo-province-022','geo','province','นครศรีธรรมราช','["นครศรีธรรมราช"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-023','geo','province','นครสวรรค์','["นครสวรรค์"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-024','geo','province','นนทบุรี','["นนทบุรี"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-025','geo','province','นราธิวาส','["นราธิวาส"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-026','geo','province','น่าน','["น่าน"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-027','geo','province','บึงกาฬ','["บึงกาฬ"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-028','geo','province','บุรีรัมย์','["บุรีรัมย์"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-029','geo','province','ปทุมธานี','["ปทุมธานี"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-030','geo','province','ประจวบคีรีขันธ์','["ประจวบคีรีขันธ์"]','จังหวัดในภาคตะวันตกของประเทศไทย','{"region":"ภาคตะวันตก"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-031','geo','province','ปราจีนบุรี','["ปราจีนบุรี"]','จังหวัดในภาคตะวันออกของประเทศไทย','{"region":"ภาคตะวันออก"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-032','geo','province','ปัตตานี','["ปัตตานี"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-033','geo','province','พระนครศรีอยุธยา','["พระนครศรีอยุธยา","อยุธยา"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-034','geo','province','พังงา','["พังงา"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-035','geo','province','พัทลุง','["พัทลุง"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-036','geo','province','พิจิตร','["พิจิตร"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-037','geo','province','พิษณุโลก','["พิษณุโลก"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-038','geo','province','เพชรบุรี','["เพชรบุรี"]','จังหวัดในภาคตะวันตกของประเทศไทย','{"region":"ภาคตะวันตก"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-039','geo','province','เพชรบูรณ์','["เพชรบูรณ์"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-040','geo','province','แพร่','["แพร่"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-041','geo','province','พะเยา','["พะเยา"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-042','geo','province','ภูเก็ต','["ภูเก็ต"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-043','geo','province','มหาสารคาม','["มหาสารคาม"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-044','geo','province','มุกดาหาร','["มุกดาหาร"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-045','geo','province','แม่ฮ่องสอน','["แม่ฮ่องสอน"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-046','geo','province','ยโสธร','["ยโสธร"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-047','geo','province','ยะลา','["ยะลา"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-048','geo','province','ร้อยเอ็ด','["ร้อยเอ็ด"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-049','geo','province','ระนอง','["ระนอง"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-050','geo','province','ระยอง','["ระยอง"]','จังหวัดในภาคตะวันออกของประเทศไทย','{"region":"ภาคตะวันออก"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-051','geo','province','ราชบุรี','["ราชบุรี"]','จังหวัดในภาคตะวันตกของประเทศไทย','{"region":"ภาคตะวันตก"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-052','geo','province','ลพบุรี','["ลพบุรี"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-053','geo','province','ลำปาง','["ลำปาง"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-054','geo','province','ลำพูน','["ลำพูน"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-055','geo','province','เลย','["เลย"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-056','geo','province','ศรีสะเกษ','["ศรีสะเกษ"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-057','geo','province','สกลนคร','["สกลนคร"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-058','geo','province','สงขลา','["สงขลา"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-059','geo','province','สตูล','["สตูล"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-060','geo','province','สมุทรปราการ','["สมุทรปราการ"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-061','geo','province','สมุทรสงคราม','["สมุทรสงคราม"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-062','geo','province','สมุทรสาคร','["สมุทรสาคร"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-063','geo','province','สระแก้ว','["สระแก้ว"]','จังหวัดในภาคตะวันออกของประเทศไทย','{"region":"ภาคตะวันออก"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-064','geo','province','สระบุรี','["สระบุรี"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-065','geo','province','สิงห์บุรี','["สิงห์บุรี"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-066','geo','province','สุโขทัย','["สุโขทัย"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-067','geo','province','สุพรรณบุรี','["สุพรรณบุรี"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-068','geo','province','สุราษฎร์ธานี','["สุราษฎร์ธานี"]','จังหวัดในภาคใต้ของประเทศไทย','{"region":"ภาคใต้"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-069','geo','province','สุรินทร์','["สุรินทร์"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-070','geo','province','หนองคาย','["หนองคาย"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-071','geo','province','หนองบัวลำภู','["หนองบัวลำภู"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-072','geo','province','อ่างทอง','["อ่างทอง"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-073','geo','province','อำนาจเจริญ','["อำนาจเจริญ"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-074','geo','province','อุดรธานี','["อุดรธานี"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-075','geo','province','อุตรดิตถ์','["อุตรดิตถ์"]','จังหวัดในภาคเหนือของประเทศไทย','{"region":"ภาคเหนือ"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-076','geo','province','อุทัยธานี','["อุทัยธานี"]','จังหวัดในภาคกลางของประเทศไทย','{"region":"ภาคกลาง"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1'),
  ('geo-province-077','geo','province','อุบลราชธานี','["อุบลราชธานี"]','จังหวัดในภาคตะวันออกเฉียงเหนือของประเทศไทย','{"region":"ภาคอีสาน"}','[]','{"name":"thai-geo-seed","url":"local://database/init/03-seed-thai-geo.sql"}',0.80,'v1')
ON DUPLICATE KEY UPDATE
  name_th = VALUES(name_th),
  aliases = VALUES(aliases),
  description = VALUES(description),
  attributes = VALUES(attributes),
  source = VALUES(source),
  confidence = VALUES(confidence),
  version = VALUES(version),
  updated_at = CURRENT_TIMESTAMP;
