/**
 * agents/conductor.ts — Phase C lightweight orchestrator
 *
 * Vertical-slice orchestrator. Given a user message + chat options, it
 * runs a deterministic graph of agent steps and emits public-safe
 * AgentEvents through the supplied `emit` callback. The actual draft
 * text is produced by composeAnswer() — for this slice the answer is a
 * Thai-led structured plan generated by deterministic templates so the
 * vertical slice is testable without an LLM round-trip. Real Ollama
 * streaming through the Concierge is C-3.5 follow-up.
 *
 * The orchestrator never emits private reasoning. Every event passes
 * through the public-safe gate before being written.
 */

import { randomUUID } from "node:crypto";
import {
  newEnvelope,
  type AgentEvent,
  type AgentEventType,
  type AgentId,
} from "./events";
import { checkAgentEventSafe } from "./eventGuard";
import { selectProvider, type ChatMode } from "../providers/router";
import {
  classifyIntent,
  type ChatIntent,
} from "../services/intentClassifier";
import { checkNaturalness } from "../services/naturalnessGuard";
import { dispatchAgents, synthesizeAnswer } from "./parallelDispatch";
import { dispatchTool } from "./toolDispatch";

export interface ConductorOptions {
  message: string;
  sessionId?: string;
  preferredMode?: ChatMode;
  preferredProviderId?: string;
  userTier?: "guest" | "user" | "admin";
  capabilityLevel?: number;
}

export type EmitFn = (ev: AgentEvent) => void;

export interface RunResult {
  runId: string;
  messageId: string;
  finalText: string;
  intent: ChatIntent;
  providerId: string | null;
  model: string | null;
  events: number;
}

interface ComposeContext {
  intent: ChatIntent;
  query: string;
  facts: string[];
}

function composeAnswer(ctx: ComposeContext): string {
  switch (ctx.intent) {
    case "greeting":
      return composeGreetingAnswer();
    case "planning-broad":
      return composePlanningBroadAnswer(ctx.query, ctx.facts);
    case "weather":
      return composeWeatherAnswer(ctx.query, ctx.facts);
    case "calc":
      return composeCalcAnswer(ctx.query);
    case "code":
      return composeCodeAnswer(ctx.query);
    case "map":
      return composeMapAnswer(ctx.query);
    default:
      return composeGeneralAnswer(ctx.query);
  }
}

function composeGreetingAnswer(): string {
  return "สวัสดีครับ! ยินดีต้อนรับสู่ INNOMCP 🤝 มีอะไรให้ช่วยไหมครับ?";
}

function composePlanningBroadAnswer(query: string, facts: string[]): string {
  const factLine =
    facts.length > 0
      ? facts.map((f) => `• ${f}`).join("\n")
      : "• ยังไม่มีข้อมูลภายนอก ใช้แนวทางแบบเชิงเหตุผลก่อน";
  return [
    "ขออนุญาตเสนอแนวทางก่อนครับ จะวางแผนแบบหลายปัจจัยเพื่อให้ตอบโจทย์ตรงสุด",
    "",
    "**เกณฑ์ที่จะใช้คัดเลือก**",
    "1) ความเสี่ยงฝน (ใช้ค่าเฉลี่ยรายภาค + พยากรณ์รายสัปดาห์ของกรมอุตุฯ)",
    "2) การเดินทาง (ระยะทางจากกรุงเทพ/สนามบินใหญ่ + ความสะดวกขนส่งสาธารณะ)",
    "3) ความพร้อมสถานที่จัดงาน (จำนวนห้องประชุม ความจุ ราคา)",
    "",
    "**สมมติฐานเริ่มต้น (ปรับได้ตามที่ระบุ)**",
    "• ช่วงเวลา: ฤดูฝน (พฤษภาคม–กันยายน)",
    "• ขนาดผู้เข้าร่วม: 50–150 คน",
    "• เริ่มต้นจากกรุงเทพฯ และเปิดรับจังหวัดนอกภาคกลาง",
    "",
    "**ผลที่ตรวจไว้แล้ว**",
    factLine,
    "",
    "**สิ่งที่ผมต้องการเพื่อสรุปจังหวัด 3 อันดับแรก**",
    "1) เดือนเป้าหมาย (เพื่อ pull พยากรณ์ที่แม่นที่สุด)",
    "2) จำนวนผู้เข้าร่วม (ส่งผลต่อขนาดห้องและงบประมาณ)",
    "3) เมืองตั้งต้นการเดินทาง (เพื่อจัดอันดับโดยระยะทาง)",
    "",
    "ระบุได้กี่ข้อก็พอครับ ที่เหลือผมใช้ค่าตั้งต้นแล้วเสนอ shortlist ให้",
  ].join("\n");
}

function composeWeatherAnswer(query: string, facts: string[]): string {
  const factLine = facts.length > 0 ? facts.map((f) => `• ${f}`).join("\n") : "";
  return [
    "ขออนุญาตสรุปอากาศตามที่ถามครับ",
    factLine,
    "",
    "หากต้องการข้อมูลรายชั่วโมงหรือเฉพาะอำเภอ บอกผมเพิ่มได้นะครับ",
  ]
    .filter(Boolean)
    .join("\n");
}

function composeCalcAnswer(query: string): string {
  return `ผมคำนวณตามคำถาม "${query.trim()}" ให้ — เส้นทางนี้เป็นแบบกำหนดได้ (deterministic) จึงไม่ต้องใช้โมเดลภาษา ผลที่ได้จะแสดงในเซสชันถัดไปครับ`;
}

function composeCodeAnswer(query: string): string {
  return `เริ่มแก้โจทย์โค้ดให้นะครับ จะใช้โมเดล qwen2.5-coder:7b เป็นหลัก เพราะอยู่ในเครื่องและพอกับงานนี้ — รบกวนแชร์โค้ดหรือ stack trace ที่เกี่ยวข้องด้วยครับ`;
}

function composeMapAnswer(query: string): string {
  return "สำหรับคำขอเกี่ยวกับแผนที่ ผมจะแสดงในส่วนคอมโพเนนต์แผนที่โดยตรง — ส่งพิกัดหรือชื่อพื้นที่มาได้เลยครับ";
}

function composeGeneralAnswer(query: string): string {
  return `ผมรับโจทย์ "${query.trim()}" แล้ว — ตอบเป็นภาษาไทยให้กระชับและตรงประเด็น หากต้องการละเอียดกว่านี้บอกได้ครับ`;
}

/**
 * Safe emit wrapper — runs the public-safe gate, suppresses on failure
 * and emits a clean fallback event instead. Returns true if the original
 * was emitted, false if it was rejected.
 */
function safeEmit(emit: EmitFn, ev: AgentEvent, expectedToolUsage: boolean): boolean {
  const guard = checkAgentEventSafe(ev, { expectedToolUsage });
  if (!guard.ok) {
    const fallback: AgentEvent = newEnvelope({
      runId: ev.runId,
      messageId: ev.messageId,
      type: "fallback",
      publicSummary: "เหตุการณ์ภายในถูกปรับให้ปลอดภัยก่อนเผยแพร่",
      agentId: "conductor",
    });
    fallback.fallbackReason = guard.reason;
    emit(fallback);
    return false;
  }
  emit(ev);
  return true;
}

function emitStarted(
  emit: EmitFn,
  runId: string,
  messageId: string,
  agentId: AgentId,
  publicSummary: string,
  expectedToolUsage: boolean
): void {
  const ev = newEnvelope({
    runId,
    messageId,
    type: "agent_started",
    publicSummary,
    agentId,
  });
  safeEmit(emit, ev, expectedToolUsage);
}

function emitFact(
  emit: EmitFn,
  runId: string,
  messageId: string,
  agentId: AgentId,
  publicSummary: string,
  confidence: number,
  expectedToolUsage: boolean
): void {
  const ev = newEnvelope({
    runId,
    messageId,
    type: "fact_found",
    publicSummary,
    agentId,
  });
  ev.confidence = confidence;
  safeEmit(emit, ev, expectedToolUsage);
}

/**
 * Run the orchestrator end-to-end. Calls `emit` for each event produced
 * and returns the final run summary. The emitter implementation decides
 * how to deliver events (SSE write, in-memory buffer, etc.).
 */
export async function runConductor(
  opts: ConductorOptions,
  emit: EmitFn
): Promise<RunResult> {
  const runId = randomUUID();
  const messageId = randomUUID();
  const cls = classifyIntent(opts.message);
  const userTier = opts.userTier ?? "guest";
  const capabilityLevel = opts.capabilityLevel ?? (userTier === "guest" ? 50 : 100);
  const userModeSummary =
    userTier === "guest"
      ? `Guest ${capabilityLevel}%: ใช้บริบทและเครื่องมือแบบจำกัด`
      : userTier === "admin"
        ? `Admin ${capabilityLevel}%: เปิดความสามารถเต็ม`
        : `User ${capabilityLevel}%: เปิดความสามารถเต็ม`;

  // Fire agents concurrently — they emit events while conductor runs.
  // Use a shared liveOutputs object so the race-timeout can still use
  // partial results from agents that finished before the deadline.
  const liveOutputs: Record<string, string> = {};
  const agentResultPromise = (process.env.PARALLEL_AGENTS !== "0")
    ? dispatchAgents(cls.intent, opts.message, runId, messageId, emit, liveOutputs)
    : Promise.resolve({} as Record<string, string>);

  // Fire MCP tool in parallel for tool-requiring intents (weather, map).
  // Result lands in liveOutputs["__tool__"] which synthesizeAnswer prefers.
  const toolPromise = dispatchTool(cls.intent, opts.message, runId, messageId, emit, liveOutputs)
    .catch(() => undefined);

  const startedEv = newEnvelope({
    runId,
    messageId,
    type: "agent_run_started",
    publicSummary: `เริ่มประมวลคำขอ (${userModeSummary})`,
    agentId: "conductor",
  });
  safeEmit(emit, startedEv, cls.expectedToolUsage);

  const routeEv = newEnvelope({
    runId,
    messageId,
    type: "route_selected",
    publicSummary: routeSummaryFor(cls.intent),
    agentId: "conductor",
  });
  safeEmit(emit, routeEv, cls.expectedToolUsage);

  // Pick a provider for the composer. The actual composition is
  // deterministic in this slice, but the broker call demonstrates the
  // contract and surfaces it to the panel.
  const broker = selectProvider({
    mode: opts.preferredMode || "local",
    capabilities: ["thai-naturalness"],
  });
  const provider = broker.provider;
  const providerId = provider?.id ?? null;
  const model = provider?.model ?? null;

  const brokerEv = newEnvelope({
    runId,
    messageId,
    type: "agent_started",
    publicSummary: provider
      ? `${broker.reason}`
      : "ยังไม่มีผู้ให้บริการที่ตรงเงื่อนไข จะใช้คำตอบเชิงโครงสร้าง",
    agentId: "broker",
  });
  brokerEv.provider = providerId ?? undefined;
  brokerEv.model = model ?? undefined;
  safeEmit(emit, brokerEv, cls.expectedToolUsage);

  // Per-intent agent involvement (deterministic — no LLM in this slice)
  const facts: string[] = [];
  if (cls.intent === "planning-broad" || cls.intent === "weather") {
    emitStarted(
      emit,
      runId,
      messageId,
      "weather-analyst",
      "ประเมินความเสี่ยงฝนรายภาคในช่วงเวลาที่เกี่ยวข้อง",
      cls.expectedToolUsage
    );
    emitFact(
      emit,
      runId,
      messageId,
      "weather-analyst",
      "ภาคกลางและภาคอีสานตอนล่างมีโอกาสฝนเฉลี่ยน้อยกว่าภาคเหนือในเดือนกลางฤดูฝน",
      0.65,
      cls.expectedToolUsage
    );
    facts.push(
      "ภาคกลาง/อีสานตอนล่าง: ฝนเฉลี่ยน้อยกว่าภาคเหนือในเดือนกลางฤดูฝน"
    );
  }

  if (cls.intent === "planning-broad") {
    emitStarted(
      emit,
      runId,
      messageId,
      "geo-planner",
      "ประเมินความสะดวกการเดินทางและสนามบินใกล้เคียง",
      cls.expectedToolUsage
    );
    emitFact(
      emit,
      runId,
      messageId,
      "geo-planner",
      "เมืองที่มีสนามบินภายในประเทศและรถสาธารณะครบทำให้ลดความเสี่ยงด้านโลจิสติกส์",
      0.6,
      cls.expectedToolUsage
    );
    facts.push("จังหวัดที่มีสนามบินภายในประเทศ ลดความเสี่ยงเดินทาง");
  }

  // Concierge composes the answer (deterministic in this slice)
  emitStarted(
    emit,
    runId,
    messageId,
    "concierge",
    "เริ่มเรียบเรียงคำตอบเป็นภาษาไทย",
    cls.expectedToolUsage
  );

  let draft = composeAnswer({ intent: cls.intent, query: opts.message, facts });

  // Stream the draft as draft_delta events in chunks of ~80 chars so the
  // frontend can render real-time growth without LLM streaming infra.
  const chunkSize = 80;
  for (let i = 0; i < draft.length; i += chunkSize) {
    const piece = draft.slice(i, i + chunkSize);
    const deltaEv = newEnvelope({
      runId,
      messageId,
      type: "draft_delta",
      publicSummary: "ส่งคำตอบเป็นช่วงๆ",
      agentId: "concierge",
    });
    deltaEv.deltaText = piece;
    if (provider) {
      deltaEv.provider = provider.id;
      deltaEv.model = provider.model;
    }
    safeEmit(emit, deltaEv, cls.expectedToolUsage);
  }

  // Naturalness check — if it fires, replace with a Thai-led fix
  const nat = checkNaturalness(draft, {
    intent: cls.intent,
    expectedToolUsage: cls.expectedToolUsage,
    userQuery: opts.message,
  });

  if (!nat.ok) {
    const fallbackEv = newEnvelope({
      runId,
      messageId,
      type: "fallback",
      publicSummary: "พบรูปแบบคำตอบที่ยังไม่เป็นธรรมชาติพอ — ปรับใหม่",
      agentId: "stylist",
    });
    fallbackEv.fallbackReason = nat.ruleFired;
    safeEmit(emit, fallbackEv, cls.expectedToolUsage);
    draft = `${draft}\n\n(${nat.hint})`;
  }

  const critiqueEv = newEnvelope({
    runId,
    messageId,
    type: "critique",
    publicSummary:
      cls.intent === "planning-broad"
        ? "ตรวจว่าคำตอบมีเกณฑ์/สมมติฐาน/คำถามต่อ"
        : "ตรวจความครบถ้วนของคำตอบ",
    agentId: "critic",
  });
  critiqueEv.confidence = nat.ok ? 0.85 : 0.55;
  safeEmit(emit, critiqueEv, cls.expectedToolUsage);

  // Wait for MDES agents. dispatchAgents is firing events in the background;
  // liveOutputs gets populated as each agent finishes. Poll every 200ms for
  // up to 35s — exits early once any agent in priority order produces text.
  // Avoids Promise.race quirks that caused SSE to hang in prior revisions.
  const HARD_TIMEOUT_MS = 35_000;
  const POLL_INTERVAL_MS = 200;
  const pollStart = Date.now();
  const hasUsefulOutput = (o: Record<string, string>) =>
    (o["stylist"] && o["stylist"].length > 20) ||
    (o["concierge"] && o["concierge"].length > 20) ||
    (o["critic"] && o["critic"].length > 20) ||
    Object.values(o).some((t) => t.length > 20);
  // Always sleep at least 1.5s to let agents at least start emitting deltas
  await new Promise<void>((resolve) => setTimeout(resolve, 1500));
  while (Date.now() - pollStart < HARD_TIMEOUT_MS) {
    // Tool data wins immediately — no need to wait for MDES if a tool succeeded
    if (liveOutputs["__tool__"] && liveOutputs["__tool__"].length > 20) break;
    if (hasUsefulOutput(liveOutputs)) break;
    await new Promise<void>((resolve) => setTimeout(resolve, POLL_INTERVAL_MS));
  }
  // Wait briefly for tool to finish if it's still pending and no other output yet
  if (!hasUsefulOutput(liveOutputs) && !liveOutputs["__tool__"]) {
    await Promise.race([toolPromise, new Promise((r) => setTimeout(r, 5000))]);
  }
  // Suppress any uncaught rejection from the background dispatch
  agentResultPromise.catch(() => undefined);
  const enrichedText = synthesizeAnswer(liveOutputs, draft);

  const finalEv = newEnvelope({
    runId,
    messageId,
    type: "final_answer",
    publicSummary: "ส่งคำตอบสุดท้าย",
    agentId: "concierge",
  });
  finalEv.finalText = enrichedText;
  finalEv.confidence = nat.ok ? 0.78 : 0.55;
  safeEmit(emit, finalEv, cls.expectedToolUsage);

  return {
    runId,
    messageId,
    finalText: enrichedText,
    intent: cls.intent,
    providerId,
    model,
    events: 0, // emitter side counts; not tracked here
  };
}

function routeSummaryFor(intent: ChatIntent): string {
  switch (intent) {
    case "greeting":
      return "ทักทาย: ส่ง concierge + critic (MDES)";
    case "planning-broad":
      return "เลือกเส้นทางวางแผนหลายปัจจัย: อากาศ + การเดินทาง";
    case "weather":
      return "เลือกเส้นทางสรุปอากาศ";
    case "calc":
      return "เลือกเส้นทางคำนวณแบบ deterministic";
    case "code":
      return "เลือกเส้นทางช่วยเขียนโค้ด";
    case "map":
      return "เลือกเส้นทางแผนที่";
    default:
      return "เลือกเส้นทางตอบทั่วไป";
  }
}
