version: '3.8'

services:
  innomcp-node:
    container_name: innomcp-node
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3010"
    env_file:
      - .env
    environment:
      - SERVER_HOST=innomcp-node
      - SERVER_PORT=3010
    networks:
      - innomcp_network

networks:
  innomcp_network:
    name: innomcp_network
    external: true